import type {
  Client,
  DnaBrief,
  Post,
  PostBatch,
  NpsResponse,
  Report,
  DashboardStats,
  MediaFile,
} from "./types"

export const mockClients: Client[] = [
  {
    id: "client-001",
    profile_id: "profile-001",
    name: "Cutelaria Ferreira",
    logo_url: null,
    status: "active",
    plan: "growth",
    onboarding_completed_at: "2026-03-15T10:00:00Z",
    settings: {},
    created_at: "2026-03-01T10:00:00Z",
    updated_at: "2026-05-20T10:00:00Z",
  },
  {
    id: "client-002",
    profile_id: "profile-001",
    name: "W2G Design",
    logo_url: null,
    status: "active",
    plan: "starter",
    onboarding_completed_at: "2026-04-01T10:00:00Z",
    settings: {},
    created_at: "2026-04-01T10:00:00Z",
    updated_at: "2026-05-18T10:00:00Z",
  },
  {
    id: "client-003",
    profile_id: "profile-001",
    name: "Evidence Ballet",
    logo_url: null,
    status: "active",
    plan: "pro",
    onboarding_completed_at: "2026-02-10T10:00:00Z",
    settings: {},
    created_at: "2026-02-10T10:00:00Z",
    updated_at: "2026-05-28T10:00:00Z",
  },
  {
    id: "client-004",
    profile_id: "profile-001",
    name: "Embratecc",
    logo_url: null,
    status: "onboarding",
    plan: "growth",
    onboarding_completed_at: null,
    settings: {},
    created_at: "2026-05-20T10:00:00Z",
    updated_at: "2026-05-20T10:00:00Z",
  },
]

export const mockDnaBrief: DnaBrief = {
  id: "dna-001",
  client_id: "client-001",
  company_name: "Cutelaria Ferreira",
  segment: "Brindes Corporativos e Cutelaria",
  city: "São Paulo, SP",
  differentials:
    "Personalização completa em facas e brindes premium, entrega em todo Brasil, atendimento B2B especializado com prova de design antes da produção.",
  ideal_client_age: "30-55",
  ideal_client_gender: "Qualquer",
  ideal_client_pain:
    "Dificuldade em encontrar brindes corporativos que sejam únicos, duráveis e que realmente impressionem clientes e colaboradores.",
  ideal_client_dream:
    "Presentear com algo memorável que fortaleça a marca da empresa e crie conexões emocionais duradouras.",
  tone_adjectives: ["Artesanal", "Premium", "Confiável", "Especialista"],
  tone_avoid: "Linguagem muito técnica, gírias, tom excessivamente informal",
  tone_example:
    "Cada peça carrega a identidade da sua empresa. Facas personalizadas que não são apenas presentes — são memórias.",
  posting_days: ["tuesday", "thursday", "saturday"],
  posting_frequency: 3,
  platform: "instagram_facebook",
  content_themes: [
    "Bastidores de produção",
    "Cases de clientes",
    "Produtos em destaque",
    "Dicas de cuidados",
    "Personalizações especiais",
  ],
  ai_notes: "Priorizar imagens de alta qualidade, produto sempre em destaque. Evitar muito texto no post.",
  version: 2,
  created_at: "2026-03-15T10:00:00Z",
  updated_at: "2026-05-10T10:00:00Z",
}

export const mockPosts: Post[] = [
  {
    id: "post-001",
    client_id: "client-001",
    batch_id: "batch-001",
    status: "sent_for_approval",
    platform: "instagram_facebook",
    caption:
      "Cada detalhe conta quando o presente precisa impressionar. ✨\n\nNossa linha de facas personalizadas para brindes corporativos traz o símbolo da sua empresa gravado com precisão — para aquele momento que fica na memória.\n\nSolicite seu orçamento no link da bio.\n\n#BrindesCorporativos #CutelariaFerreira #PersonalizadoParaVocê",
    image_url: "https://images.unsplash.com/photo-1612528443702-f6741f70a049?w=800",
    image_prompt: "Professional knife on dark wood, company logo engraved, studio lighting, luxury feel",
    scheduled_for: "2026-06-03T10:00:00Z",
    published_at: null,
    rejection_reason: null,
    ai_generation_metadata: { model: "claude-3-5-sonnet", tokens: 342 },
    created_at: "2026-05-28T09:00:00Z",
    updated_at: "2026-05-28T09:00:00Z",
  },
  {
    id: "post-002",
    client_id: "client-001",
    batch_id: "batch-001",
    status: "sent_for_approval",
    platform: "instagram",
    caption:
      "Bastidores: onde a magia acontece. 🔥\n\nDo aço bruto à faca personalizada — acompanhe o processo artesanal que garante qualidade em cada peça produzida aqui na Cutelaria Ferreira.\n\nQuer ver seu logo nessa peça?\n\n#ArtesanatoBrasileiro #Cutelaria #FelitoAMão",
    image_url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800",
    image_prompt: "Blacksmith workshop, hands working on hot metal, dramatic lighting, artisanal atmosphere",
    scheduled_for: "2026-06-05T10:00:00Z",
    published_at: null,
    rejection_reason: null,
    ai_generation_metadata: { model: "claude-3-5-sonnet", tokens: 298 },
    created_at: "2026-05-28T09:00:00Z",
    updated_at: "2026-05-28T09:00:00Z",
  },
  {
    id: "post-003",
    client_id: "client-002",
    batch_id: "batch-002",
    status: "approved",
    platform: "instagram_facebook",
    caption:
      "Mobiliário que fala a língua do seu escritório. 🏢\n\nNa W2G Design, cada projeto corporativo começa com uma escuta. Qual é a identidade do seu espaço?\n\n#MóveisCorpotativos #DesignDeInteriores #W2GDesign",
    image_url: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800",
    image_prompt: "Modern corporate office interior, clean furniture, natural light, minimalist aesthetic",
    scheduled_for: "2026-06-02T10:00:00Z",
    published_at: null,
    rejection_reason: null,
    ai_generation_metadata: { model: "claude-3-5-sonnet", tokens: 189 },
    created_at: "2026-05-26T09:00:00Z",
    updated_at: "2026-05-27T14:00:00Z",
  },
  {
    id: "post-004",
    client_id: "client-003",
    batch_id: "batch-003",
    status: "scheduled",
    platform: "instagram",
    caption:
      "O ballet que cabe no seu orçamento. 💃\n\nKit completo Evidence: sapatilha, meia-ponta e maillot com a qualidade que professoras recomendam há 15 anos.\n\nLink na bio para ver toda a coleção.\n\n#EvidenceBallet #Ballet #DançaBrasileira",
    image_url: "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800",
    image_prompt: "Ballet dancer in full outfit, studio setting, artistic lighting, elegant pose",
    scheduled_for: "2026-06-02T08:00:00Z",
    published_at: null,
    rejection_reason: null,
    ai_generation_metadata: { model: "claude-3-5-sonnet", tokens: 210 },
    created_at: "2026-05-25T09:00:00Z",
    updated_at: "2026-05-27T10:00:00Z",
  },
  {
    id: "post-005",
    client_id: "client-003",
    batch_id: "batch-003",
    status: "published",
    platform: "instagram_facebook",
    caption:
      "Atacado Evidence: para quem vende qualidade. 🛍️\n\nSe você tem loja de artigos para dança, conheça nossa linha atacado com condições especiais para lojistas.\n\nWhatsApp no link da bio.\n\n#AtacadoBallet #LojistasEvidence #Evidence",
    image_url: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=800",
    image_prompt: "Ballet shoes and accessories flatlay, clean white background, retail display style",
    scheduled_for: "2026-05-28T08:00:00Z",
    published_at: "2026-05-28T08:03:12Z",
    rejection_reason: null,
    ai_generation_metadata: { model: "claude-3-5-sonnet", tokens: 187 },
    created_at: "2026-05-22T09:00:00Z",
    updated_at: "2026-05-28T08:03:12Z",
  },
  {
    id: "post-006",
    client_id: "client-001",
    batch_id: null,
    status: "generated",
    platform: "instagram_facebook",
    caption:
      "Presenteie com história. 🎁\n\nUma faca gravada com o nome da empresa, entregue em caixa premium — esse é o tipo de brinde que ninguém esquece.\n\nSolicite agora e receba em até 15 dias.\n\n#BrindeEspecial #CutelariaFerreira",
    image_url: null,
    image_prompt: "Premium gift box with engraved knife, elegant packaging, dark background with warm light",
    scheduled_for: null,
    published_at: null,
    rejection_reason: null,
    ai_generation_metadata: { model: "claude-3-5-sonnet", tokens: 156 },
    created_at: "2026-05-30T09:00:00Z",
    updated_at: "2026-05-30T09:00:00Z",
  },
  {
    id: "post-007",
    client_id: "client-004",
    batch_id: null,
    status: "draft",
    platform: "instagram_facebook",
    caption: "",
    image_url: null,
    image_prompt: null,
    scheduled_for: null,
    published_at: null,
    rejection_reason: null,
    ai_generation_metadata: {},
    created_at: "2026-05-30T09:00:00Z",
    updated_at: "2026-05-30T09:00:00Z",
  },
]

export const mockNpsResponses: NpsResponse[] = [
  {
    id: "nps-001",
    client_id: "client-001",
    score: 9,
    category: "promoter",
    trigger: "monthly",
    comment: "Excelente serviço! Os posts ficam muito profissionais.",
    created_at: "2026-05-28T10:00:00Z",
  },
  {
    id: "nps-002",
    client_id: "client-002",
    score: 8,
    category: "passive",
    trigger: "post_approval",
    comment: "Gostei muito, poderia ter mais variação nos temas.",
    created_at: "2026-05-25T10:00:00Z",
  },
  {
    id: "nps-003",
    client_id: "client-003",
    score: 10,
    category: "promoter",
    trigger: "monthly",
    comment: "Incrível! Economizei horas de trabalho todo mês.",
    created_at: "2026-05-20T10:00:00Z",
  },
  {
    id: "nps-004",
    client_id: "client-001",
    score: 7,
    category: "passive",
    trigger: "post_approval",
    comment: null,
    created_at: "2026-05-01T10:00:00Z",
  },
]

export const mockReport: Report = {
  id: "report-001",
  client_id: "client-001",
  week_reference: "2026-W22",
  metrics: {
    reach: 4280,
    impressions: 7650,
    engagement_rate: 4.7,
    new_followers: 23,
    posts_published: 3,
    top_post_url: "https://www.instagram.com/p/example",
  },
  ai_insights:
    "Semana com desempenho acima da média. O post de bastidores de produção gerou 2x mais engajamento que a média histórica — recomendo aumentar a frequência desse tipo de conteúdo. A taxa de engajamento de 4.7% está 1.2pp acima da média do segmento (3.5%). Para a próxima semana, sugerimos incluir um Reels curto mostrando o processo de personalização.",
  sent_at: "2026-05-26T08:00:00Z",
  created_at: "2026-05-26T07:00:00Z",
}

export const mockMediaFiles: MediaFile[] = [
  {
    id: "media-001",
    client_id: "client-001",
    file_name: "produto-faca-premium.jpg",
    file_url: "https://images.unsplash.com/photo-1612528443702-f6741f70a049?w=400",
    file_type: "image/jpeg",
    file_size: 245000,
    tags: ["produto", "premium", "faca"],
    uploaded_at: "2026-05-10T10:00:00Z",
  },
  {
    id: "media-002",
    client_id: "client-001",
    file_name: "logo-cutelaria-principal.png",
    file_url: "https://images.unsplash.com/photo-1614680376739-414d95ff43df?w=400",
    file_type: "image/png",
    file_size: 85000,
    tags: ["logo", "marca"],
    uploaded_at: "2026-03-01T10:00:00Z",
  },
  {
    id: "media-003",
    client_id: "client-001",
    file_name: "oficina-producao.jpg",
    file_url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=400",
    file_type: "image/jpeg",
    file_size: 312000,
    tags: ["bastidores", "producao", "artesanal"],
    uploaded_at: "2026-04-15T10:00:00Z",
  },
  {
    id: "media-004",
    client_id: "client-001",
    file_name: "embalagem-presente.jpg",
    file_url: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=400",
    file_type: "image/jpeg",
    file_size: 198000,
    tags: ["embalagem", "presente", "premium"],
    uploaded_at: "2026-04-20T10:00:00Z",
  },
]

export const mockDashboardStats: DashboardStats = {
  total_clients: 4,
  active_clients: 3,
  posts_this_week: 8,
  pending_approvals: 2,
  avg_nps: 8.5,
  posts_published_month: 24,
}
