import type {
  Client,
  DnaBrief,
  Post,
  PostBatch,
  NpsResponse,
  Report,
  DashboardStats,
  MediaFile,
} from "./types"

export const mockClients: Client[] = [
  {
    id: "client-001",
    profile_id: "profile-001",
    name: "SLR Engenharia",
    logo_url: null,
    status: "active",
    plan: "growth",
    onboarding_completed_at: "2026-04-10T10:00:00Z",
    settings: {},
    created_at: "2026-04-01T10:00:00Z",
    updated_at: "2026-05-28T10:00:00Z",
  },
  {
    id: "client-002",
    profile_id: "profile-001",
    name: "SLR Properties",
    logo_url: null,
    status: "active",
    plan: "growth",
    onboarding_completed_at: "2026-04-10T10:00:00Z",
    settings: {},
    created_at: "2026-04-01T10:00:00Z",
    updated_at: "2026-05-28T10:00:00Z",
  },
]

export const mockDnaBrief: DnaBrief = {
  id: "dna-001",
  client_id: "client-001",
  company_name: "SLR Engenharia",
  segment: "Engenharia e Construção Civil",
  city: "São Paulo, SP",
  differentials:
    "Projetos de engenharia com excelência técnica e cumprimento rigoroso de prazos. Equipe especializada em obras corporativas, industriais e residenciais de alto padrão. Mais de 15 anos de mercado com carteira diversificada.",
  ideal_client_age: "35-60",
  ideal_client_gender: "Qualquer",
  ideal_client_pain:
    "Obras atrasadas, orçamentos estourados e falta de transparência durante o processo construtivo.",
  ideal_client_dream:
    "Entregar o projeto no prazo e dentro do orçamento, com comunicação clara e resultado final que supere as expectativas.",
  tone_adjectives: ["Técnico", "Confiável", "Sólido", "Preciso"],
  tone_avoid: "Linguagem muito informal, promessas vagas, exageros",
  tone_example:
    "Engenharia é comprometimento. Cada projeto SLR é entregue com precisão técnica e no prazo combinado — porque sua obra merece quem respeita o cronograma.",
  posting_days: ["tuesday", "thursday"],
  posting_frequency: 2,
  platform: "instagram_facebook",
  content_themes: [
    "Obras em andamento",
    "Projetos entregues",
    "Equipe e bastidores",
    "Dicas técnicas",
    "Cases de sucesso",
  ],
  ai_notes: "Sempre destacar credibilidade, prazo e qualidade técnica. Imagens de obras reais quando disponíveis.",
  version: 1,
  created_at: "2026-04-10T10:00:00Z",
  updated_at: "2026-04-10T10:00:00Z",
}

export const mockDnaBriefProperties: DnaBrief = {
  id: "dna-002",
  client_id: "client-002",
  company_name: "SLR Properties",
  segment: "Incorporação Imobiliária e Gestão de Imóveis",
  city: "São Paulo, SP",
  differentials:
    "Incorporadora com foco em empreendimentos de alto padrão. Gestão completa desde a captação do terreno até a entrega das chaves. Parcerias com os melhores escritórios de arquitetura do país.",
  ideal_client_age: "30-55",
  ideal_client_gender: "Qualquer",
  ideal_client_pain:
    "Insegurança na hora de investir em imóvel — medo de construtoras que não entregam, valorização incerta e falta de transparência.",
  ideal_client_dream:
    "Investir com segurança em um imóvel que valorize e que seja entregue conforme prometido, com acabamento premium.",
  tone_adjectives: ["Sofisticado", "Seguro", "Exclusivo", "Transparente"],
  tone_avoid: "Tom muito técnico, jargão jurídico, pressão de vendas excessiva",
  tone_example:
    "Investir é sobre confiar em quem constrói. A SLR Properties entrega mais que imóveis — entrega patrimônio com a assinatura de quem não abre mão da excelência.",
  posting_days: ["monday", "wednesday", "friday"],
  posting_frequency: 3,
  platform: "instagram_facebook",
  content_themes: [
    "Lançamentos e empreendimentos",
    "Evolução das obras",
    "Decoração e arquitetura",
    "Dicas de investimento imobiliário",
    "Depoimentos de clientes",
  ],
  ai_notes: "Linguagem aspiracional e sofisticada. Foco em valorização e segurança do investimento.",
  version: 1,
  created_at: "2026-04-10T10:00:00Z",
  updated_at: "2026-04-10T10:00:00Z",
}

export const mockPosts: Post[] = [
  {
    id: "post-001",
    client_id: "client-001",
    batch_id: "batch-001",
    status: "sent_for_approval",
    platform: "instagram_facebook",
    caption:
      "Obra entregue. Prazo cumprido. ✅\n\nMais um projeto industrial concluído pela equipe SLR Engenharia — dentro do cronograma e com acabamento que faz diferença.\n\nCada detalhe é executado com precisão técnica. É assim que construímos reputação.\n\n📐 Orçamento no link da bio.\n\n#SLREngenharia #EngenhariaDeResultado #ObraIndustrial #ConstruçãoCivil",
    image_url: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800",
    image_prompt: "Modern industrial construction site, finished building exterior, clean lines, professional photography",
    scheduled_for: "2026-06-03T10:00:00Z",
    published_at: null,
    rejection_reason: null,
    ai_generation_metadata: { model: "claude-sonnet-4-6", tokens: 312 },
    created_at: "2026-05-29T09:00:00Z",
    updated_at: "2026-05-29T09:00:00Z",
  },
  {
    id: "post-002",
    client_id: "client-001",
    batch_id: "batch-001",
    status: "sent_for_approval",
    platform: "instagram_facebook",
    caption:
      "Por trás de toda grande obra, há uma equipe que não aceita menos que o melhor. 🏗️\n\nNossos engenheiros e técnicos no canteiro — garantindo que cada etapa do projeto seja executada com rigor e segurança.\n\nÉ assim na SLR: da planta à entrega, comprometimento total.\n\n#SLREngenharia #TimeDeEngenharia #Construção #BastidaresDeObra",
    image_url: "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=800",
    image_prompt: "Engineers in hard hats reviewing blueprints at construction site, professional team, golden hour light",
    scheduled_for: "2026-06-05T10:00:00Z",
    published_at: null,
    rejection_reason: null,
    ai_generation_metadata: { model: "claude-sonnet-4-6", tokens: 278 },
    created_at: "2026-05-29T09:00:00Z",
    updated_at: "2026-05-29T09:00:00Z",
  },
  {
    id: "post-003",
    client_id: "client-002",
    batch_id: "batch-002",
    status: "approved",
    platform: "instagram_facebook",
    caption:
      "Morar bem começa com quem escolhe bem. 🏙️\n\nO novo empreendimento SLR Properties foi desenvolvido para quem entende que um imóvel é muito mais que quatro paredes — é patrimônio, estilo de vida e segurança para o futuro.\n\nUnidades com metragem a partir de 80m². Acabamento premium. Localização privilegiada.\n\n📲 Saiba mais no link da bio.\n\n#SLRProperties #ImóvelDeAltoPardrão #Investimento #LançamentoImobiliário",
    image_url: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800",
    image_prompt: "Luxury apartment building exterior at dusk, modern architecture, premium real estate, city backdrop",
    scheduled_for: "2026-06-02T10:00:00Z",
    published_at: null,
    rejection_reason: null,
    ai_generation_metadata: { model: "claude-sonnet-4-6", tokens: 298 },
    created_at: "2026-05-27T09:00:00Z",
    updated_at: "2026-05-28T14:00:00Z",
  },
  {
    id: "post-004",
    client_id: "client-002",
    batch_id: "batch-002",
    status: "scheduled",
    platform: "instagram",
    caption:
      "Valorização garantida? Só com quem conhece o mercado. 📈\n\nNa SLR Properties, cada empreendimento é desenvolvido após análise criteriosa de localização, potencial de valorização e demanda real do mercado.\n\nInvista com quem tem histórico. Invista com quem entrega.\n\n#SLRProperties #InvestimentoImobiliário #ValorizaçãoImobiliária #MercadoImobiliárioSP",
    image_url: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800",
    image_prompt: "Aerial view of São Paulo skyline with luxury buildings, golden hour, investment concept",
    scheduled_for: "2026-06-04T09:00:00Z",
    published_at: null,
    rejection_reason: null,
    ai_generation_metadata: { model: "claude-sonnet-4-6", tokens: 245 },
    created_at: "2026-05-27T09:00:00Z",
    updated_at: "2026-05-28T10:00:00Z",
  },
  {
    id: "post-005",
    client_id: "client-001",
    batch_id: null,
    status: "published",
    platform: "instagram_facebook",
    caption:
      "15 anos construindo confiança. 🏆\n\nDesde 2011, a SLR Engenharia transforma projetos em realidade — com mais de 200 obras entregues e clientes que voltam porque confiam no nosso trabalho.\n\nObrigado a cada cliente que fez parte dessa história.\n\n#SLREngenharia #15Anos #Engenharia #LegadoDeObras",
    image_url: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=800",
    image_prompt: "Collage of construction achievements, team photo, milestone celebration, professional brand",
    scheduled_for: "2026-05-28T10:00:00Z",
    published_at: "2026-05-28T10:02:44Z",
    rejection_reason: null,
    ai_generation_metadata: { model: "claude-sonnet-4-6", tokens: 198 },
    created_at: "2026-05-23T09:00:00Z",
    updated_at: "2026-05-28T10:02:44Z",
  },
  {
    id: "post-006",
    client_id: "client-002",
    batch_id: null,
    status: "generated",
    platform: "instagram_facebook",
    caption:
      "O apartamento dos seus sonhos existe. E está mais perto do que você imagina. 🔑\n\nConheça o novo lançamento SLR Properties: plantas inteligentes, acabamento de alto padrão e toda a segurança de uma incorporadora com histórico comprovado.\n\nAgenda uma visita: link na bio.\n\n#SLRProperties #NovoProjeto #ImóvelDesonho #SPImoveis",
    image_url: null,
    image_prompt: "Modern luxury apartment interior, open living space, designer furniture, floor-to-ceiling windows with city view",
    scheduled_for: null,
    published_at: null,
    rejection_reason: null,
    ai_generation_metadata: { model: "claude-sonnet-4-6", tokens: 221 },
    created_at: "2026-05-31T09:00:00Z",
    updated_at: "2026-05-31T09:00:00Z",
  },
]

export const mockNpsResponses: NpsResponse[] = [
  {
    id: "nps-001",
    client_id: "client-001",
    score: 9,
    category: "promoter",
    trigger: "monthly",
    comment: "Os posts refletem muito bem a seriedade da nossa empresa. Ótimo trabalho!",
    created_at: "2026-05-28T10:00:00Z",
  },
  {
    id: "nps-002",
    client_id: "client-002",
    score: 10,
    category: "promoter",
    trigger: "post_approval",
    comment: "Conteúdo sofisticado e alinhado com o posicionamento da SLR Properties. Superou as expectativas.",
    created_at: "2026-05-26T10:00:00Z",
  },
  {
    id: "nps-003",
    client_id: "client-001",
    score: 8,
    category: "passive",
    trigger: "post_approval",
    comment: "Bom, mas gostaríamos de mais posts mostrando obras em andamento.",
    created_at: "2026-05-15T10:00:00Z",
  },
  {
    id: "nps-004",
    client_id: "client-002",
    score: 9,
    category: "promoter",
    trigger: "monthly",
    comment: null,
    created_at: "2026-05-10T10:00:00Z",
  },
]

export const mockReport: Report = {
  id: "report-001",
  client_id: "client-001",
  week_reference: "2026-W22",
  metrics: {
    reach: 3840,
    impressions: 6920,
    engagement_rate: 4.2,
    new_followers: 18,
    posts_published: 2,
    top_post_url: "https://www.instagram.com/p/example",
  },
  ai_insights:
    "Semana consistente para a SLR Engenharia. O post de bastidores da equipe gerou 1.8x mais engajamento que o post de obra finalizada — o público responde bem ao conteúdo humano. Taxa de engajamento de 4.2% está acima da média do segmento de construção civil (2.8%). Recomendo aumentar a frequência de posts mostrando a equipe em ação. Para a próxima semana, sugerimos um post de case completo com antes/depois de uma obra.",
  sent_at: "2026-05-26T08:00:00Z",
  created_at: "2026-05-26T07:00:00Z",
}

export const mockMediaFiles: MediaFile[] = [
  {
    id: "media-001",
    client_id: "client-001",
    file_name: "obra-industrial-fachada.jpg",
    file_url: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400",
    file_type: "image/jpeg",
    file_size: 312000,
    tags: ["obra", "industrial", "fachada"],
    uploaded_at: "2026-05-10T10:00:00Z",
  },
  {
    id: "media-002",
    client_id: "client-001",
    file_name: "equipe-engenharia.jpg",
    file_url: "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=400",
    file_type: "image/jpeg",
    file_size: 278000,
    tags: ["equipe", "engenheiros", "canteiro"],
    uploaded_at: "2026-05-12T10:00:00Z",
  },
  {
    id: "media-003",
    client_id: "client-002",
    file_name: "empreendimento-fachada.jpg",
    file_url: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=400",
    file_type: "image/jpeg",
    file_size: 345000,
    tags: ["empreendimento", "fachada", "alto-padrao"],
    uploaded_at: "2026-05-08T10:00:00Z",
  },
  {
    id: "media-004",
    client_id: "client-002",
    file_name: "apartamento-interior.jpg",
    file_url: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=400",
    file_type: "image/jpeg",
    file_size: 289000,
    tags: ["interior", "apartamento", "luxo"],
    uploaded_at: "2026-05-09T10:00:00Z",
  },
]

export const mockDashboardStats: DashboardStats = {
  total_clients: 2,
  active_clients: 2,
  posts_this_week: 4,
  pending_approvals: 2,
  avg_nps: 9.0,
  posts_published_month: 6,
}
